/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author LOQ
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        
        namapemesanField.putClientProperty(
            "JTextField.placeholderText",
            "Nama sesuai KTP"
        );

        nomorhpField.putClientProperty(
            "JTextField.placeholderText",
            "08xxxxxxxxxx"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KelasGroup = new javax.swing.ButtonGroup();
        namapemesanLabel = new javax.swing.JLabel();
        nomorhpLabel = new javax.swing.JLabel();
        kotatujuanLabel = new javax.swing.JLabel();
        namapemesanField = new javax.swing.JTextField();
        nomorhpField = new javax.swing.JTextField();
        kotatujuanCombo = new javax.swing.JComboBox<>();
        kelasLabel = new javax.swing.JLabel();
        ekonomiRadio = new javax.swing.JRadioButton();
        bisnisRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        bagasiCheck = new javax.swing.JCheckBox();
        makanCheck = new javax.swing.JCheckBox();
        asuransiCheck = new javax.swing.JCheckBox();
        catatanLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanArea = new javax.swing.JTextArea();
        pesanButton = new javax.swing.JButton();
        temaToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemesanan Tiket Travel");

        namapemesanLabel.setText("Nama Pemesan");

        nomorhpLabel.setText("Nomor HP");

        kotatujuanLabel.setText("Kota Tujuan");

        kotatujuanCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        kelasLabel.setText("Kelas");

        KelasGroup.add(ekonomiRadio);
        ekonomiRadio.setText("Ekonomi");

        KelasGroup.add(bisnisRadio);
        bisnisRadio.setSelected(true);
        bisnisRadio.setText("Bisnis");
        bisnisRadio.addActionListener(this::bisnisRadioActionPerformed);

        KelasGroup.add(eksekutifRadio);
        eksekutifRadio.setText("Eksekutif");

        jLabel1.setText("Fasilitas");

        bagasiCheck.setText("Bagasi");

        makanCheck.setText("Makan");

        asuransiCheck.setText("Asuransi");

        catatanLabel.setText("Catatan");

        catatanArea.setColumns(20);
        catatanArea.setRows(3);
        jScrollPane1.setViewportView(catatanArea);

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(namapemesanLabel)
                        .addComponent(nomorhpLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(kotatujuanLabel)
                    .addComponent(kelasLabel)
                    .addComponent(jLabel1)
                    .addComponent(catatanLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pesanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(temaToggle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bagasiCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(makanCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(asuransiCheck))
                    .addComponent(namapemesanField)
                    .addComponent(nomorhpField)
                    .addComponent(kotatujuanCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ekonomiRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bisnisRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eksekutifRadio))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namapemesanLabel)
                    .addComponent(namapemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorhpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorhpLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kotatujuanLabel)
                    .addComponent(kotatujuanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelasLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ekonomiRadio)
                        .addComponent(bisnisRadio)
                        .addComponent(eksekutifRadio)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bagasiCheck)
                        .addComponent(makanCheck)
                        .addComponent(asuransiCheck)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(catatanLabel)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanButton)
                    .addComponent(temaToggle))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
    String nama = namapemesanField.getText();
    String nomorHp = nomorhpField.getText();
    String kota = kotatujuanCombo.getSelectedItem().toString();

    String kelas = "";
    if (ekonomiRadio.isSelected()) {
        kelas = "Ekonomi";
    } else if (bisnisRadio.isSelected()) {
        kelas = "Bisnis";
    } else if (eksekutifRadio.isSelected()) {
        kelas = "Eksekutif";
    }

    StringBuilder fasilitas = new StringBuilder();

    if (bagasiCheck.isSelected()) {
        fasilitas.append("Bagasi");
    }

    if (makanCheck.isSelected()) {
        if (fasilitas.length() > 0) {
            fasilitas.append(", ");
        }
        fasilitas.append("Makan");
    }

    if (asuransiCheck.isSelected()) {
        if (fasilitas.length() > 0) {
            fasilitas.append(", ");
        }
        fasilitas.append("Asuransi");
    }

    if (fasilitas.length() == 0) {
        fasilitas.append("Tidak ada");
    }

    String catatan = catatanArea.getText();

    String ringkasan =
            "=== RINGKASAN PEMESANAN ===\n\n"
            + "Nama Pemesan : " + nama + "\n"
            + "Nomor HP     : " + nomorHp + "\n"
            + "Kota Tujuan  : " + kota + "\n"
            + "Kelas        : " + kelas + "\n"
            + "Fasilitas    : " + fasilitas + "\n"
            + "Catatan      : " + catatan;

    JOptionPane.showMessageDialog(
            this,
            ringkasan,
            "Ringkasan Pemesanan",
            JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
        if (temaToggle.isSelected()) {
        FlatDarkLaf.setup();
    } else {
        FlatLightLaf.setup();
    }

    javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_temaToggleActionPerformed

    private void bisnisRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisnisRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bisnisRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup KelasGroup;
    private javax.swing.JCheckBox asuransiCheck;
    private javax.swing.JCheckBox bagasiCheck;
    private javax.swing.JRadioButton bisnisRadio;
    private javax.swing.JTextArea catatanArea;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JComboBox<String> kotatujuanCombo;
    private javax.swing.JLabel kotatujuanLabel;
    private javax.swing.JCheckBox makanCheck;
    private javax.swing.JTextField namapemesanField;
    private javax.swing.JLabel namapemesanLabel;
    private javax.swing.JTextField nomorhpField;
    private javax.swing.JLabel nomorhpLabel;
    private javax.swing.JButton pesanButton;
    private javax.swing.JToggleButton temaToggle;
    // End of variables declaration//GEN-END:variables
}
